// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Adorn Hair & Beauty Nikol",
  category: "Beauty Parlour",
  address: "\nShantiniketan-2 Hindva, First Floor 07, Shantiniketan II, Nr. Mc. Donalds Nikol, Beside Pavilion Mall • Hindva, Near McDonald's, New India Colony, Nikol, Ahmedabad, Gujarat 380049",
  phone: "\n090168 81166",
  email: "",
  website: "http://topedgeai.com/",
  mapUrl: "https://www.google.com/maps/place/Adorn+Hair+%26+Beauty+Nikol/@23.0504878,72.6680099,17z/data=!3m1!4b1!4m6!3m5!1s0x395e8721ffccb03f:0x8020a0b50f8b9e4b!8m2!3d23.0504878!4d72.6680099!16s%2Fg%2F11fyx9ty5p?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0504878",
  longitude: "72.6680099",
  rating: "",
  reviewsCount: "1518",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.png",
  images: ["/images/gmap_1780036546839_0.jpg", "/images/gmap_1780036547199_1.jpg", "/images/gmap_1780036547455_2.jpg", "/images/gmap_1780036547734_3.jpg", "/images/gmap_1780036547997_4.jpg", "/images/gmap_1780036548053_5.jpg", "/images/gmap_1780036548371_6.jpg", "/images/gmap_1780036548388_7.jpg", "/images/gmap_1780036548722_8.jpg", "/images/gmap_1780036548743_9.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Beauty elevated in Nikol",
  heroDescription: "Experience the art of beauty at Adorn Hair & Beauty Nikol, where every visit is a journey of self-discovery. Our expert stylists and therapists are dedicated to providing you with an unparalleled experience. Located in the heart of Shantiniketan-2 Hindva, we invite you to indulge in our world of beauty and wellness.",
  aboutTitle: "The Story of Adorn",
  aboutText: "At Adorn Hair & Beauty Nikol, we're passionate about helping you unlock your true potential. Our salon, nestled in the vibrant Shantiniketan-2 Hindva area, is a haven for those seeking to escape the ordinary and experience the extraordinary. Our team of skilled professionals are committed to delivering exceptional service, tailored to your unique needs and preferences. With a focus on innovation and creativity, we strive to make every visit a memorable one.",
  services: [
    { icon: "💇‍♀️", title: "Hair Spa", description: "Our luxurious hair spa treatments are designed to nourish and rejuvenate your locks, leaving you with a radiant glow" },
    { icon: "💅", title: "Nail Art", description: "From classic to trendy, our expert nail technicians will help you achieve the perfect look to match your unique style" },
    { icon: "🌸", title: "Mehendi", description: "Experience the traditional art of Mehendi with our skilled artists, perfect for special occasions or everyday elegance" },
    { icon: "💆‍♀️", title: "Facial Treatments", description: "Our customized facial treatments are designed to address your specific skin concerns, leaving you with a refreshed and revitalized complexion" },
    { icon: "🌹", title: "Bridal Makeup", description: "Our expert makeup artists will help you achieve the perfect look for your special day, with a focus on enhancing your natural beauty" },
    { icon: "💈", title: "Hair Coloring", description: "From subtle to bold, our hair coloring services are tailored to your unique preferences, ensuring a look that's truly yours" }
  ],
  whyChooseUs: [
    { icon: "💯", title: "Personalized Service", description: "At Adorn Hair & Beauty Nikol, we take the time to understand your unique needs and preferences, delivering a truly personalized experience" },
    { icon: "🌿", title: "Natural Ingredients", description: "We're committed to using only the finest, natural ingredients in our treatments, ensuring a healthier and more sustainable approach to beauty" },
    { icon: "👥", title: "Experienced Team", description: "Our team of skilled professionals are dedicated to providing exceptional service, with a focus on building long-term relationships with our clients" },
    { icon: "💼", title: "State-of-the-Art Facilities", description: "Our salon is equipped with the latest technology and amenities, ensuring a comfortable and relaxing experience for all our clients" }
  ],
  testimonials: [
    { name: "Maanvi Jain", role: "Regular Client", text: "I've been visiting Adorn Hair & Beauty Nikol for months now, and I'm always impressed by the exceptional service and attention to detail. The hair spa treatment is my favorite!", rating: 5 },
    { name: "Mihika Mehta", role: "Bride-to-Be", text: "The bridal makeup services at Adorn Hair & Beauty Nikol are truly exceptional. The team is professional, talented, and dedicated to making you look and feel your best on your special day.", rating: 5 },
    { name: "Manasi Patel", role: "Mother of the Bride", text: "I recently visited Adorn Hair & Beauty Nikol with my daughter for her bridal makeup trial, and we were both blown away by the expertise and creativity of the team. The Mehendi service is also a must-try!", rating: 5 }
  ],
  pricing: { description: "Affordable luxury for every budget", packages: [{ name: "Essential", price: "₹469", period: "per session", description: "Our basic package includes a consultation, hair cut, and styling", features: ["Consultation", "Hair Cut", "Styling"], popular: false, cta: "Book Now" },
    { name: "Deluxe", price: "₹949", period: "per session", description: "Our deluxe package includes a consultation, hair cut, coloring, and styling", features: ["Consultation", "Hair Cut", "Coloring", "Styling"], popular: true, cta: "Book Now" },
    { name: "Premium", price: "₹1349", period: "per session", description: "Our premium package includes a consultation, hair cut, coloring, styling, and a complimentary facial treatment", features: ["Consultation", "Hair Cut", "Coloring", "Styling", "Facial Treatment"], popular: false, cta: "Book Now" }] },
  ctaTitle: "Experience the Art of Beauty",
  ctaDescription: "Book your appointment today and discover a world of beauty and wellness at Adorn Hair & Beauty Nikol",
  ctaButtonText: "Book Your Appointment",
  metaDescription: "Beauty salon in Nikol, Ahmedabad",
};

export const siteConfig = {
  layout: "swiss-typography",
  theme: "elegant",
  sections: ["gallery", "aria", "about", "lazy", "skip", "pricing", "whatsapp", "contact", "google", "a", "social"],
  heroVariant: "diagonal-layout",
  navStyle: "sticky-animated-nav",
  animationStyle: "scroll-triggered-reveals",
  cardStyle: "rounded-none border-l-4 border-l-primary",
  darkMode: false,
};
