// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Adorn Hair & Beauty Nikol",
  category: "Beauty Parlour",
  address: "\nShantiniketan-2 Hindva, First Floor 07, Shantiniketan II, Nr. Mc. Donalds Nikol, Beside Pavilion Mall • Hindva, Near McDonald's, New India Colony, Nikol, Ahmedabad, Gujarat 380049",
  phone: "\n090168 81166",
  email: "",
  website: "http://topedgeai.com/",
  mapUrl: "https://www.google.com/maps/place/Adorn+Hair+%26+Beauty+Nikol/@23.0504878,72.6680099,17z/data=!3m1!4b1!4m6!3m5!1s0x395e8721ffccb03f:0x8020a0b50f8b9e4b!8m2!3d23.0504878!4d72.6680099!16s%2Fg%2F11fyx9ty5p?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0504878",
  longitude: "72.6680099",
  rating: "",
  reviewsCount: "1518",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.png",
  images: ["/images/gmap_1780037307917_0.jpg", "/images/gmap_1780037307950_1.jpg", "/images/gmap_1780037307969_2.jpg", "/images/gmap_1780037307989_3.jpg", "/images/gmap_1780037308017_4.jpg", "/images/gmap_1780037308056_5.jpg", "/images/gmap_1780037308075_6.jpg", "/images/gmap_1780037308093_7.jpg", "/images/gmap_1780037308120_8.jpg", "/images/gmap_1780037308141_9.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Beauty Redefined in Nikol",
  heroDescription: "Experience the finest hair and beauty services at Adorn Hair & Beauty Nikol, located in the heart of Ahmedabad. Our skilled professionals cater to your every need, providing personalized attention and care. From haircuts to beauty treatments, we have it all.",
  aboutTitle: "Our Story: Where Beauty Meets Passion",
  aboutText: "Nestled in the bustling area of Shantiniketan-2 Hindva, our salon is a haven for those seeking exceptional beauty treatments. Our team of experts is dedicated to providing top-notch services, ensuring that every client leaves feeling pampered and satisfied. We take pride in our work, using only the finest products and techniques to deliver outstanding results.",
  services: [
    { icon: "💇", title: "Mehendi Application", description: "Our skilled artists create intricate designs for special occasions" },
    { icon: "💅", title: "Hair Color and Styling", description: "From subtle highlights to vibrant colors, our experts will transform your look" },
    { icon: "💆", title: "Facial and Skincare", description: "Rejuvenate your skin with our range of facials and treatments, tailored to your skin type" },
    { icon: "👠", title: "Bridal Makeup and Hair", description: "Our team will help you look stunning on your big day, with customized packages to suit your needs" },
    { icon: "💈", title: "Haircut and Grooming", description: "From trims to complete makeovers, our experts will help you achieve the perfect look" },
    { icon: "👗", title: "Beauty Consultations", description: "Get personalized advice on skincare, haircare, and makeup from our experienced professionals" }
  ],
  whyChooseUs: [
    { icon: "🌟", title: "Experienced Professionals", description: "Our team has years of experience in the beauty industry, ensuring that you receive the best possible service" },
    { icon: "🏠", title: "Convenient Location", description: "Located in the heart of Nikol, our salon is easily accessible and convenient for clients from all over Ahmedabad" },
    { icon: "💯", title: "High-Quality Products", description: "We use only the finest products and equipment to ensure that our clients receive the best possible results" },
    { icon: "📝", title: "Personalized Service", description: "Our team takes the time to understand your needs and provides personalized attention to ensure that you leave feeling satisfied" }
  ],
  testimonials: [
    { name: "Hemali Gandhi", role: "Bride", text: "I was thrilled with the bridal makeup and hair services provided by Adorn Hair & Beauty Nikol. The team was professional and courteous, and I received countless compliments on my big day.", rating: 5 },
    { name: "Harshita Mehta", role: "Regular Client", text: "I've been visiting Adorn Hair & Beauty Nikol for months now, and I'm always impressed with the quality of service. The team is friendly and knowledgeable, and they always make me feel welcome.", rating: 5 },
    { name: "Hiren Shah", role: "Groom", text: "I opted for the haircut and grooming services at Adorn Hair & Beauty Nikol, and I was blown away by the results. The team is skilled and attentive, and I would highly recommend them to anyone looking for a great haircut.", rating: 5 }
  ],
  pricing: { description: "Our pricing packages are designed to fit your needs and budget", packages: [{ name: "Basic Beauty Package", price: "₹555", period: "per session", description: "Includes a 30-minute facial and a basic haircut", features: ["Facial", "Haircut"], popular: false, cta: "Book Now" },
    { name: "Deluxe Hair and Beauty Package", price: "₹1111", period: "per session", description: "Includes a 60-minute facial, a haircut, and a makeup session", features: ["Facial", "Haircut", "Makeup"], popular: true, cta: "Book Now" },
    { name: "Premium Bridal Package", price: "₹2222", period: "per session", description: "Includes a comprehensive bridal makeup and hair package, complete with trials and consultations", features: ["Bridal Makeup", "Bridal Hair", "Trials", "Consultations"], popular: false, cta: "Book Now" }] },
  ctaTitle: "Transform Your Look Today",
  ctaDescription: "Book an appointment with our expert team and experience the best in hair and beauty services. We can't wait to welcome you to Adorn Hair & Beauty Nikol!",
  ctaButtonText: "Book Your Appointment",
  metaDescription: "Adorn Hair & Beauty Nikol: Expert hair and beauty services in Ahmedabad",
};

export const siteConfig = {
  layout: "swiss-typography",
  theme: "elegant",
  sections: ["gallery", "aria", "about", "lazy", "skip", "pricing", "whatsapp", "contact", "google", "a", "social"],
  heroVariant: "diagonal-layout",
  navStyle: "sticky-animated-nav",
  animationStyle: "scroll-triggered-reveals",
  cardStyle: "rounded-none border-l-4 border-l-primary",
  darkMode: false,
};
